######################################################################
# Automatically generated by qmake (3.1) Sat May 27 06:32:21 2023
######################################################################

TEMPLATE = app
TARGET = ../bin/alignment

INCLUDEPATH += .

######################################################################
# decoder headers
INCLUDEPATH += ../decoder/include ../decoder/evio-5.2
# decoder lib
LIBS += -L../decoder/lib -ldecoder

######################################################################
# gem headers
INCLUDEPATH += ../gem/include ../gem/third_party
# gem lib
LIBS += -L../gem/lib -lgem

######################################################################
# tracking headers
INCLUDEPATH += ../tracking_dev/include
# tracking lib
LIBS += -L../tracking_dev/lib -ltracking_dev

######################################################################
# root headers
INCLUDEPATH += ${ROOTSYS}/include
# root libs
LIBS += -L${ROOTSYS}/lib -lCore -lRIO -lNet \
	-lHist -lGraf -lGraf3d -lGpad -lTree \
	-lRint -lPostscript -lMatrix -lPhysics \
	-lGui -lRGL -lMathCore

MOC_DIR = moc
OBJECTS_DIR = obj

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += matrix.h \
           standard_align.h \
           ToyModel.h \

SOURCES += matrix.cpp \
           standard_align.cpp \
           test.cpp \
           ToyModel.cpp \
