#!/bin/bash

source setup_env.sh

RUN=$1

echo "analyzing run" $RUN

# replay run
#./bin/replay.app/Contents/MacOS/replay -c 0 -t 0 -z 1 -n -1 --tracking off --pedestal database/gem_ped_505.dat --common_mode database/CommonModeRange_505.txt /Users/xinzhan/test/For_Pietro/fermilab_beamtest_$RUN.evio.0
#./bin/replay.app/Contents/MacOS/replay -c 0 -t 0 -z 1 -n -1 --tracking off --pedestal database/gem_ped_860.dat --common_mode database/CommonModeRange_860.txt /Users/xinzhan/test/evio_data/prad2/gem0gem1_000$RUN.evio.00156
./bin/replay.app/Contents/MacOS/replay -c 0 -t 0 -z 1 -n -1 --tracking on --pedestal database/gem_ped_860.dat --common_mode database/CommonModeRange_860.txt /Users/xinzhan/test/evio_data/prad2/gem0gem1_000$RUN.evio.00156


# plot run
#ROOT_FILE='scripts/plot_quality_results.cpp("Rootfiles/cluster_0_fermilab_beamtest_'${RUN}'.root_data_quality_check.root")'
ROOT_FILE='scripts/plot_quality_results.cpp("Rootfiles/cluster_0_gem0gem1_000'${RUN}'.root_data_quality_check.root")'
root -b -q $ROOT_FILE

# show run
#evince Rootfiles/cluster_0_vtp_trigger_test_$RUN.evio.0.root_data_quality_check.root.pdf 
#open Rootfiles/cluster_0_fermilab_beamtest_$RUN.root_data_quality_check.root.pdf 
open Rootfiles/cluster_0_gem0gem1_000$RUN.root_data_quality_check.root.pdf 
