#!/bin/bash

source setup_env.sh

# pedestal file
PEDESTAL_FILE="database/gem_ped_186.dat"
COMMON_MODE_FILE="database/CommonModeRange_186.txt"

# raw data file path
RAW_DIR="$HOME/test/evio_data"

# analysis setup
RUN=-1
TOTAL_EVENTS=-1
NCORE=1

if [ $# -lt 1 ] || [ $# -gt 3 ]; then
    echo "Usage: $0 RUN [TOTAL_EVENTS_PER_SPLIT] [NJOBS]"
    echo "       [TOTAL_EVENTS_PER_SPLIT] can be a rough close number, e.g. 3456 can be rounded up to the larger side 4000"
    exit 1
fi

RUN=$1
[ $# -ge 2 ] && TOTAL_EVENTS=$2
[ $# -ge 3 ] && NCORE=$3

echo "Analyzing run $RUN for $TOTAL_EVENTS events with $NCORE job(s)"

# get ready all file splits
list_evio_splits() {
    local pattern="$RAW_DIR/fermilab_beamtest_$RUN.evio.*"
    local files=($(ls $pattern 2>/dev/null))

    if [ ${#files[@]} -eq 0 ]; then
        echo "No files found for run $RUN"
        return 2
    fi

    printf "%s\n" "${files[@]}"
}

# show all files that will be analyzed
echo "files queued for analysis: "
files=$(list_evio_splits)
for f in "${files[@]}"; do
    echo $f
done

# replay run
for f in "${files[@]}"; do
    echo "analyzing file: $f"
    ./bin/replay -c 0 -t 0 -z 1 -n $TOTAL_EVENTS --tracking off --pedestal $PEDESTAL_FILE --common_mode $COMMON_MODE_FILE $f
done

exit

# plot run
ROOT_FILE='scripts/plot_quality_results.cpp("Rootfiles/cluster_0_vtp_trigger_test_'${RUN}'.evio.0.root_data_quality_check.root")'
root -b -q $ROOT_FILE

# show run
evince Rootfiles/cluster_0_vtp_trigger_test_$RUN.evio.0.root_data_quality_check.root.pdf 

