# set database dir
DB_DIR = ${THIS_DIR}/../database
CONF_DIR = ${THIS_DIR}/../config

# GEM DAQ mapping information
GEM Map = ${DB_DIR}/gem_map_srs_frib.txt

# default GEM pedestal
GEM Common Mode = ${DB_DIR}/CommonModeRange_1082.txt
GEM Pedestal = ${DB_DIR}/gem_ped_1082.dat

# gem tracking config file
GEM Tracking Config = ${CONF_DIR}/gem_tracking.conf

# VTP Pedestal Subtraction Mode enabled or not (yes/no), if enabled, offset will be subtracted online
VTP Pedestal Subtraction = no

# GEM cluster method configuration file
GEM Cluster Configuration = ${THIS_DIR}/gem_cluster.conf

# some default settings for GEM APVs
Default Time Samples = 6
Default Common Mode Threshold = 20
Default Zero Suppression Threshold = 5
Default Cross Talk Threshold = 8

# resolution information (mm)
Position Resolution = 0.08
