######################################################################
# Automatically generated by qmake (3.1) Sat Nov 7 17:18:28 2020
######################################################################

TEMPLATE = app
TARGET = test

QMAKE_CXXFLAGS = -std=c++11

######################################################################
# self headers
INCLUDEPATH += . ./include


######################################################################
# decoder headers
INCLUDEPATH += ../include
#decoder libs
LIBS += -L../lib -ldecoder


######################################################################
# coda headers
INCLUDEPATH += ${CODA}/common/include
# coda libs
LIBS += -L${CODA}/Linux-x86_64/lib -levio


######################################################################
# root headers
INCLUDEPATH += ${ROOTSYS}/include
# root libs
LIBS += -L${ROOTSYS}/lib -lCore -lRIO -lNet \
	-lHist -lGraf -lGraf3d -lGpad -lTree \
	-lRint -lPostscript -lMatrix -lPhysics \
	-lGui -lRGL


######################################################################
# moc dir
MOC = moc


######################################################################
# obj dir
OBJECTS_DIR = obj


######################################################################
# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0


######################################################################
# Input path
HEADERS += 

######################################################################
# source path
SOURCES += test.cpp \ 

